apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g0dyl05mx-nodejs
  janus-idp.io/tekton: g0dyl05mx-nodejs
  backstage.io/kubernetes-id: g0dyl05mx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g0dyl05mx-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
